
[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = false

[[language]]
name = "go"
language-servers = [ "gopls" ] 
auto-format = true
formatter = { command = "goimports" }

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]
