foreground              #FFFFFF
background              #08000B
selection_foreground    #08000B
selection_background    #FFFFFF
cursor                  #7C2177
cursor_text_color       #FFFFFF

active_tab_foreground     #08000B
active_tab_background     #23076F
inactive_tab_foreground   #23076F
inactive_tab_background   #08000B

# black
color0      #462952
color8      #80578F

# red
color1      #FFCCFC
color9      #F0AAEC

# green
color2      #ECCCFF
color10     #D6AAF0

# yellow
color3      #DACCFF
color11     #BDAAF0

# blue
color4      #D19AE6
color12     #D19AE6

# magenta
color5      #C99AE6
color13     #C99AE6

# cyan
color6      #AE9AE6
color14     #AE9AE6

# white
color7      #FFCCFC
color15     #F0AAEC
