-- Generated by nwg-displays on 2026-08-12 at 22:54:29. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.0",
    position = "66x0",
    scale = 1.3333334,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1686x479",
    scale = 1.3333334
})
