-- █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
-- █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

-- Set your personal hyprland configuration here

-- Start pyprland daemon
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Using hypridle to start hyprlock
-- lock after 10 mins, sleep after 15 mins // install swayidle
-- exec-once = swayidle -w timeout 900 'swaylock' timeout 1800 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'
require("keybindings")

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        repeat_rate = 60,
        repeat_delay = 250,
        -- sensitivity = 1 #mouse sensitivity
        numlock_by_default = true,
        left_handed = false,
        follow_mouse = true,
        float_switch_override_focus = false,
    },
    -- device {
    --   name=logitech-mx-master-2s
    --   sensitivity = 1.0
    -- }
})
