-- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
-- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

-- See https://wiki.hyprland.org/Configuring/Window-Rules/

-- '$&' is a hyde specific shorthand for "override" \\ analogous to a reference
-- This symbol indicates that the following values will override the default configuration
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local _ = "override"

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "^(firefox)$",
    },
    opacity = "0.90",
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "^(Brave-browser)$",
    },
    opacity = "0.90 $& 0.90 $& 1",
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = "^(code-oss)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
})

hl.window_rule({
    name = "windowrule-4",
    match = {
        class = "^([Cc]ode)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
})

hl.window_rule({
    name = "windowrule-5",
    match = {
        class = "^(code-url-handler)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
})

hl.window_rule({
    name = "windowrule-6",
    match = {
        class = "^(code-insiders-url-handler)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
})

hl.window_rule({
    name = "windowrule-7",
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
})

hl.window_rule({
    name = "windowrule-8",
    match = {
        class = "^(org.kde.dolphin)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
})

hl.window_rule({
    name = "windowrule-9",
    match = {
        class = "^(org.kde.ark)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-10",
    match = {
        class = "^(nwg-look)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-11",
    match = {
        class = "^(qt5ct)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-12",
    match = {
        class = "^(qt6ct)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-13",
    match = {
        class = "^(kvantummanager)$",
    },
    opacity = "0.80 $& 0.80 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-14",
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-15",
    match = {
        class = "^(blueman-manager)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-16",
    match = {
        class = "^(nm-applet)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-17",
    match = {
        class = "^(nm-connection-editor)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-18",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
    float = true,
})

hl.window_rule({
    name = "windowrule-19",
    match = {
        class = "^(polkit-gnome-authentication-agent-1)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-20",
    match = {
        class = "^(org.freedesktop.impl.portal.desktop.gtk)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-21",
    match = {
        class = "^(org.freedesktop.impl.portal.desktop.hyprland)$",
    },
    opacity = "0.80 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-22",
    match = {
        class = "^([Ss]team)$",
    },
    opacity = "0.70 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-23",
    match = {
        class = "^(steamwebhelper)$",
    },
    opacity = "0.70 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-24",
    match = {
        class = "^([Ss]potify)$",
    },
    opacity = "0.70 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-25",
    match = {
        initial_title = "^(Spotify Free)$",
    },
    opacity = "0.70 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-26",
    match = {
        initial_title = "^(Spotify Premium)$",
    },
    opacity = "0.70 $& 0.70 $& 1",
})

hl.window_rule({
    name = "windowrule-27",
    match = {
        class = "^(com.github.rafostar.Clapper)$",
    },
    opacity = "0.90 0.90",
})

hl.window_rule({
    name = "windowrule-28",
    match = {
        class = "^(com.github.tchx84.Flatseal)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-29",
    match = {
        class = "^(hu.kramo.Cartridges)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-30",
    match = {
        class = "^(com.obsproject.Studio)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-31",
    match = {
        class = "^(gnome-boxes)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-32",
    match = {
        class = "^(vesktop)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-33",
    match = {
        class = "^(discord)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-34",
    match = {
        class = "^(WebCord)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-35",
    match = {
        class = "^(ArmCord)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-36",
    match = {
        class = "^(app.drey.Warp)$",
    },
    opacity = "0.80 0.80",
    float = true,
})

hl.window_rule({
    name = "windowrule-37",
    match = {
        class = "^(net.davidotek.pupgui2)$",
    },
    opacity = "0.80 0.80",
    float = true,
})

hl.window_rule({
    name = "windowrule-38",
    match = {
        class = "^(yad)$",
    },
    opacity = "0.80 0.80",
    float = true,
})

hl.window_rule({
    name = "windowrule-39",
    match = {
        class = "^(Signal)$",
    },
    opacity = "0.80 0.80",
    float = true,
})

hl.window_rule({
    name = "windowrule-40",
    match = {
        class = "^(io.github.alainm23.planify)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-41",
    match = {
        class = "^(io.gitlab.theevilskeleton.Upscaler)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-42",
    match = {
        class = "^(com.github.unrud.VideoDownloader)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-43",
    match = {
        class = "^(io.gitlab.adhami3310.Impression)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-44",
    match = {
        class = "^(io.missioncenter.MissionCenter)$",
    },
    opacity = "0.80 0.80",
    float = true,
})

hl.window_rule({
    name = "windowrule-45",
    match = {
        class = "^(io.github.flattool.Warehouse)$",
    },
    opacity = "0.80 0.80",
})

hl.window_rule({
    name = "windowrule-46",
    match = {
        class = "^(org.kde.dolphin)$",
        title = "^(Progress Dialog — Dolphin)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-47",
    match = {
        class = "^(org.kde.dolphin)$",
        title = "^(Copying — Dolphin)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-48",
    match = {
        title = "^(About Mozilla Firefox)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-49",
    match = {
        class = "^(firefox)$",
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-50",
    match = {
        class = "^(firefox)$",
        title = "^(Library)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-51",
    match = {
        class = "^(kitty)$",
        title = "^(top)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-52",
    match = {
        class = "^(kitty)$",
        title = "^(btop)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-53",
    match = {
        class = "^(kitty)$",
        title = "^(htop)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-54",
    match = {
        class = "^(vlc)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-55",
    match = {
        class = "^(GitHub Desktop)$",
    },
    float = false,
})

-- windowrulev2 = float,class:^(com.github.rafostar.Clapper)$ # Clapper-Gtk
hl.window_rule({
    name = "windowrule-56",
    match = {
        class = "^(eog)$",
    },
    float = true,
})

-- windowrulev2 = float,class:^(io.github.alainm23.planify)$ # planify-Gtk
-- windowrulev2 = float,class:^(io.gitlab.theevilskeleton.Upscaler)$ # Upscaler-Gtk
-- windowrulev2 = float,class:^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gkk
-- windowrulev2 = float,class:^(io.gitlab.adhami3310.Impression)$ # Impression-Gtk

-- common modals
-- windowrule = float,initialTitle:^(Open File)$
-- windowrule = float,title:^(Choose Files)$
-- windowrule = float,title:^(Save As)$
-- windowrule = float,title:^(Confirm to replace files)$
-- windowrule = float,title:^(File Operation Progress)$
hl.window_rule({
    name = "windowrule-57",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
})

-- █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
-- █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

-- layerrule = blur,rofi
-- layerrule = ignorezero,rofi
-- layerrule = blur,notifications
-- layerrule = ignorezero,notifications
-- layerrule = blur,swaync-notification-window
-- layerrule = ignorezero,swaync-notification-window
-- layerrule = blur,swaync-control-center
-- layerrule = ignorezero,swaync-control-center
-- layerrule = blur,logout_dialog

-- terminal tags
hl.window_rule({
    name = "windowrule-58",
    match = {
        class = "^(Alacritty|kitty|kitty-dropterm)$",
    },
    tag = "+terminal",
})
