#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_family                 JetBrainsMono Nerd Font
font_size                   12
