

theme = "nosferatu"

[editor]
line-number = "relative"
completion-replace = true

[keys.normal]
C-g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
C-b = [":buffer-close"]


"A-down" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
] # Move line(s) down
"A-up" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
] # Move line(s) up

C-right = "move_next_word_start"
C-left = "move_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-up = "extend_line_up"
S-down = "extend_line_down"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-up = "extend_line_up"
S-down = "extend_line_down"

[keys.select]
C-right = "extend_next_word_start"
C-left = "extend_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-up = "extend_line_up"
S-down = "extend_line_down"

g = { o = ":open \"%%P\"|altfile<ret>" }
